const SWR_KEYS = {
  GET_CART_LS: 'GET_CART_LS',
  GET_DATE_LS: 'GET_DATE_LS',

  GET_SALES_OF_USER_DB: 'GET_SALES_OF_USER_DB',
  GET_SALES_OF_USER_BY_BEST_SELLER_DB: 'GET_SALES_OF_USER_BY_BEST_SELLER_DB',
  GET_CART_PRODUCT_DETAILS_DB: 'GET_CART_PRODUCT_DETAILS_DB',
}

export default SWR_KEYS
