export const SWR_KEYS = {
  GET_CART_LS: 'GET_CART_LS',
  GET_DATE_LS: 'GET_DATE_LS',

  GET_SALES_OF_USER_DB: 'GET_SALES_OF_USER_DB',
  GET_SALES_OF_USER_BY_BEST_SELLER_DB: 'GET_SALES_OF_USER_BY_BEST_SELLER_DB',
  GET_CART_PRODUCT_DETAILS_DB: 'GET_CART_PRODUCT_DETAILS_DB',

  TOGGLE_FAV_PRODUCT: 'TOGGLE_FAV_PRODUCT',
  GET_FAV_PRODUCTS: 'GET_FAV_PRODUCTS',

  GET_UNIQUE_CATEGORY: 'GET_UNIQUE_CATEGORY',
  GET_BRANDS_OF_USER: 'GET_BRANDS_OF_USER',
  GET_BRANDS_OF_USER_FULL: 'GET_BRANDS_OF_USER_FULL',

  GET_AXIS_OF_USER: 'GET_AXIS_OF_USER',

  // Users & Staff
  GET_USERS: 'GET_USERS',
}
