import type { Metadata } from 'next'

import { Inter } from 'next/font/google'

import './globals.css'

import Navbar from '@/components/navigation/navbar'
import NavbarRx from '@/components/ui/radix/navbar/navbar-radix'

import '@radix-ui/themes/styles.css'
import { Theme, ThemePanel } from '@radix-ui/themes'

import { Providers } from '@/components/auth/providers'

import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentSession = await getServerSession(authOptions)

  return (
    <html lang="en" className={inter.className}>
      <Providers>
        <body>
          <Theme accentColor="cyan">
            {/* <Navbar session={currentSession} /> */}
            <NavbarRx session={currentSession} />
            <main>{children}</main>
            {/* <ThemePanel /> */}
          </Theme>
        </body>
      </Providers>
    </html>
  )
}
